### ISSUE TITLE
Integration fail

### ISSUE THREAD

**Issue by mhgeay** [BrevilleBro/cortex-analyzer-urlscanio#1]
Hello @BrevilleBro ,

I installed your analyzer in my personal TheHive/Cortex instance :

1. Copied three files (UrlScan_Scan.json  long.html  urlscan.py) in the main analyzers directory where I created a new directory "UrlScan".
2. Add parameters (API, private) in Cortex's application.conf file.
3. restarted Cortex, no error in log, only this :  
`2018-03-06 21:43:24,367 [INFO] from services.ExternalAnalyzerSrv in application-akka.actor.default-dispatcher-4 - Register analyzer UrlScan_Scan 1.0 (UrlScan_Scan_1_0)`
4. On TheHive GUI, UrlScan Analyzer is present ! I tested an URL and got an error : 
```
{
  "errorMessage": "Cannot run program \"sh\" (in directory \"/..../Cortex-Analyzers/analyzers/UrlscanIO\"): error=2, No such file or directory:java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n\tscala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)\n\tservices.ExternalAnalyzerSrv$$anonfun$analyze$1.apply(ExternalAnalyzerSrv.scala:87)\n\tservices.ExternalAnalyzerSrv$$anonfun$analyze$1.apply(ExternalAnalyzerSrv.scala:78)\n\tscala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)\n\tscala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)\n\takka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)\n\takka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)\n\tscala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tscala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tscala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tscala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n",
  "input": null,
  "success": false
}
```
I don't understand the link with a Bash script (Cannot run program \"sh\").

Do you have an idea ?
I think I have all requirements for your python script (I run others without issue). 

Thank you !

**Comment by BrevilleBro** [comment]
@mhgeay the folder should be named "UrlscanIO". 

Let me know if you need further help with it.

**Comment by mhgeay** [comment]
@BrevilleBro, thank you, it's works !
I forgot to read the json file... `command": "UrlscanIO/urlscan.py`
