### ISSUE TITLE
Request to modify the Readme

### ISSUE THREAD

**Issue by vi-or-die** [BrevilleBro/cortex-analyzer-urlscanio#2]
Being new to the cortex/hive project myself I had to do the following things to get this to work for me. 

For other beginners, I would reccomend a couple steps be added to your readme, at least until this is pulled into the Cortex Analyzer repo and it is handled automatically. 

Installation Steps:
1. Change directories to your cortex analyzers directory and run the following command
sudo git clone [place url for repo here]

2. Rename the file with the following command
sudo mv cortex-analyzer-urlscanio/ UrlscanIO/

3. Set the permissions on the UrlscanIO/urlscan.py file
sudo chmod 755 urlscan.py

If you receive the following error, this is by design to prevent you from leaking sensitive data to public sites. 
"errorMessage": "TLP is higher than allowed."

**Comment by BrevilleBro** [comment]
Thanks @vi-or-die; will add this to the readme.
